// Writes src/data/wornManifest.ts — the set of item ids that have a purpose-built
// worn-on-body overlay PNG under public/assets/sprites/worn/. PreloadScene gates
// its catalog-driven worn loader on this set so missing art never 404s (no
// "Failed to process file" console spam). Re-run after generating more worn art:
//   node scripts/sdart/buildWornManifest.mjs
import { readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const dir = join(ROOT, "public/assets/sprites/worn");
const ids = readdirSync(dir)
  .filter((f) => f.endsWith(".png"))
  .map((f) => f.slice(0, -4))
  .sort();

const body = `// AUTO-GENERATED by scripts/sdart/buildWornManifest.mjs — do not edit by hand.
// Item ids that ship a purpose-built worn-on-body overlay PNG
// (public/assets/sprites/worn/<id>.png). The PreloadScene worn loader gates on
// this set so a partial art batch never requests a missing file (no console
// "Failed to process file" spam) and heroDressLayout's worn-art preference only
// kicks in for ids that truly have art.

export const WORN_MANIFEST: ReadonlySet<string> = new Set([
${ids.map((id) => `  "${id}",`).join("\n")}
]);

/** True when item \`id\` has a purpose-built worn overlay PNG. */
export function hasWornArt(id: string): boolean {
  return WORN_MANIFEST.has(id);
}
`;
writeFileSync(join(ROOT, "src/data/wornManifest.ts"), body);
console.log(`wrote src/data/wornManifest.ts with ${ids.length} worn ids`);
