/**
 * Scene background images (SDXL, generated by wibu-td-designer/gen-backgrounds.mjs).
 * Loaded by PreloadScene as `bg__<id>` textures: the main-menu throne hall and
 * one battlefield backdrop per chapter theme.
 */
export const BG_IMAGES = [
  "menu-hall",
  "chapter-greenwood",
  "chapter-frost",
  "chapter-desert",
  "chapter-volcanic",
  "chapter-swamp",
  "chapter-corrupted",
  "endless-siege",
] as const;

export const bgKey = (id: string): string => `bg__${id}`;
