// src/data/heroDoll.ts
//
// Paper-doll layout for the Inventory loadout: each equipment slot mapped to the
// hero's body (helmet on the head, weapon in the hand, boots at the feet, …).
// Anchors are normalized (0..1) within the doll panel box; mirrors the design
// team's hero-doll/layout.json, nudged slightly for clean spacing.
import type { ItemSlot } from "./schema.ts";

export interface DollSlotDef {
  slot: ItemSlot;
  nx: number;        // normalized x within the panel (0..1)
  ny: number;        // normalized y within the panel (0..1)
  label: string;
  behind?: boolean;  // drawn behind the mannequin (wings)
}

export const DOLL_SLOTS: DollSlotDef[] = [
  { slot: "Helmet",    nx: 0.50, ny: 0.11, label: "Head" },
  { slot: "Amulet",    nx: 0.50, ny: 0.27, label: "Neck" },
  { slot: "Wing",      nx: 0.50, ny: 0.34, label: "Wings", behind: true },
  { slot: "BodyArmor", nx: 0.50, ny: 0.45, label: "Body" },
  { slot: "Weapon",    nx: 0.15, ny: 0.47, label: "Weapon" },
  { slot: "Gloves",    nx: 0.85, ny: 0.51, label: "Hands" },
  { slot: "Ring1",     nx: 0.15, ny: 0.69, label: "Ring I" },
  { slot: "Ring2",     nx: 0.85, ny: 0.69, label: "Ring II" },
  { slot: "Boots",     nx: 0.50, ny: 0.85, label: "Feet" },
  { slot: "Pet",       nx: 0.85, ny: 0.87, label: "Pet" },
];

/** Panel box (scene coordinates) the doll fills — left side of the loadout screen. */
export const DOLL_PANEL = { x: 26, y: 94, w: 300, h: 418 };

/** The mannequin texture key (generated by wibu-td-designer/gen-hero-doll.mjs). */
export const DOLL_BASE_KEY = "herodoll__base";
