/**
 * Jewel-icon ids — one painted 96×96 gem icon per skill jewel (generated by
 * wibu-td-designer/gen-jewels-full.mjs). Driven directly by the jewel catalog so
 * the list never drifts from the data. PreloadScene loads each as a
 * `jewel__<id>` texture.
 */
import { JEWEL_CATALOG } from "./jewels.ts";

export const JEWEL_ICON_IDS: string[] = JEWEL_CATALOG.map((jw) => jw.id);

/** Texture key for a jewel's painted icon. */
export function jewelIconKey(id: string): string {
  return `jewel__${id}`;
}
