/**
 * Skill-icon ids — one painted 96×96 icon per tower active + passive skill
 * (generated by wibu-td-designer/gen-skills-full.mjs). Driven directly by the
 * skill catalog so the list never drifts from the data. PreloadScene loads each
 * as a `skill__<id>` texture (skipping any id already in the sprite manifest, so
 * a future `gen.mjs --only=manifest` that folds these in won't double-load).
 */
import { TOWER_ACTIVES, PASSIVE_SKILLS } from "./passiveSkills.ts";
import { ACTIVE_SKILLS } from "./skills.ts";
import { skillTex } from "./assetKeys.ts";

export const SKILL_ICON_IDS: string[] = [
  ...Object.keys(TOWER_ACTIVES),
  ...Object.keys(PASSIVE_SKILLS),
  ...ACTIVE_SKILLS.map((s) => s.id), // hero active skills
];

/** Texture key for a skill's painted icon. */
export function skillIconKey(id: string): string {
  return skillTex(id);
}
