// AUTO-GENERATED by scripts/sdart/buildWornManifest.mjs — do not edit by hand.
// Item ids that ship a purpose-built worn-on-body overlay PNG
// (public/assets/sprites/worn/<id>.png). The PreloadScene worn loader gates on
// this set so a partial art batch never requests a missing file (no console
// "Failed to process file" spam) and heroDressLayout's worn-art preference only
// kicks in for ids that truly have art.

export const WORN_MANIFEST: ReadonlySet<string> = new Set([
  "aegis-of-dawn",
  "arcane-staff",
  "assassin-gloves",
  "cloth-robe",
  "dawnbreaker",
  "elven-bow",
  "fine-grimoire",
  "fine-hand-cannon",
  "fine-longbow",
  "fine-warblade",
  "fine-wizard-staff",
  "fledgling-wings",
  "heroic-hand-cannon",
  "heroic-longbow",
  "heroic-warblade",
  "heroic-wizard-staff",
  "iron-helm",
  "iron-sword",
  "leather-cap",
  "masterwork-grimoire",
  "masterwork-hand-cannon",
  "masterwork-longbow",
  "masterwork-warblade",
  "masterwork-wizard-staff",
  "mythic-hand-cannon",
  "mythic-longbow",
  "mythic-warblade",
  "mythic-wizard-staff",
  "scale-mail",
  "swift-boots",
  "tempest-wings",
  "thunder-cannon",
  "void-render",
  "worn-boots",
  "worn-gloves",
  "worn-grimoire",
  "worn-hand-cannon",
  "worn-longbow",
  "worn-warblade",
  "worn-wizard-staff",
]);

/** True when item `id` has a purpose-built worn overlay PNG. */
export function hasWornArt(id: string): boolean {
  return WORN_MANIFEST.has(id);
}
